### ISSUE TITLE
Strange crash in iOS10

### ISSUE THREAD

**Issue by IronTony** [anarchicknight/react-native-communications#35] opened 2016-10-10 11:15 UTC
Hi all,

anyone got this problem when trying to make a call?
I did this:
`<TouchableOpacity onPress={() => Communications.phonecall('01234567789', true)}>....</TouchableOpacity>`

I have the alert with the phone number and the following red screen of death.
![Uploading IMG_0003.PNG…]()

**Comment by anarchicknight** [comment] 2016-10-10 19:10
I'm wondering if apple have changed something with ios10.

Using true was always a bit of a risk as mentioned in the readme as it uses an undocumented method.

It may be that the option now needs to be removed.

The image you tried uploading seems to be missing, what was the error on the red screen?

**Comment by JiLaqi** [comment] 2016-10-14 06:19
I'm sorry，I can't see your picture(Uploading IMG_0003.PNG...)， don't know your error log.
iOS 10(XCode 8) no new restrictions with the phone.
I think your errpr is not about iOS10.
Do you add this library with RCTLinking?

AKCommunications.js
import {
	Linking,
	Platform,
} from 'react-native';

Use the library(communications-iOS) must add RCTLinking with native target.

**Comment by anarchicknight** [comment] 2016-10-14 07:58
I'm pretty sure you only need to add RCTLinking if you want to handle deep links [see here](https://facebook.github.io/react-native/docs/linking.html).

For this library it should not be needed - I don't need to add it myself on my test project for the library to work.

What would be useful for this issue is if we can find out what error @IronTony is getting so we can try and debug

**Comment by anarchicknight** [comment] 2016-10-24 21:34
any update on this issue? What was the message in the red screen?

Were you running on device or emulator?

**Comment by maluramichael** [comment] 2016-10-26 09:37
Could it be possible that there is a missing Info.plist entry?

**Comment by IronTony** [comment] 2016-10-28 14:15
Hi sorry for the late, I was running on a real device (iPhone 6, with iOS: 10.0.2).
I am trying to reproduce that specific error, but I do not have it anymore.
I thought could be a problem of Linking inclusion as @anarchicknight suggested, but it is not.

I can consider it closed, but I am stressing the functionality that uses your component, so I will come back with more data if a crash or similar will happen again.

Sorry again for the late answer

**Comment by anarchicknight** [comment] 2016-10-30 18:21
thanks - closing for now then.

Reopen if you reproduce

**Closed by anarchicknight** 2016-10-30 18:21 UTC
