### ISSUE TITLE
Crashes when cancelling phonecall with prompt

### ISSUE THREAD

**Issue by danielbh** [anarchicknight/react-native-communications#39] opened 2016-11-21 15:33 UTC
As a work around I'm disabling the prompt. Any idea on why it's doing this? Thanks.

On iOS 10.1.1
iPhone 7 actual device
React Native v0.37

**Code snippet:**

``` javascript
rncom.phonecall(number, true)
```

![img_4685](https://cloud.githubusercontent.com/assets/6653234/20488492/81c46aaa-b007-11e6-972a-e2b677c1bc2d.PNG)
![img_4686](https://cloud.githubusercontent.com/assets/6653234/20488494/84365d70-b007-11e6-83e1-a8dde9f3ddc5.PNG)

**Comment by ronaldx** [comment] 2016-11-21 17:15
same issue here.

**Comment by anarchicknight** [comment] 2016-11-21 17:17
Is this specific to RN 0.37 or did it happen in earlier versions?

I no longer have an actual iOS device to test on so may have to rely on the community to try and help resolve this

**Comment by Chooin** [comment] 2016-11-22 17:01
same issue RN 0.37

**Comment by danielbh** [comment] 2016-11-23 14:54
@anarchicknight I don't know.

**Comment by anarchicknight** [comment] 2016-11-23 14:59
Thanks.

Is anyone able to test on RN 0.36 or earlier?

I have no way of testing this on a device anymore :(

If we can't find a solution I may just remove the telprompt option - as mentioned in the readme this was always an undocumented option and not officially supported by Apple

**Comment by atdrago** [comment] 2016-12-07 07:17
@anarchicknight It reproduces in the simulator. You shouldn't need an actual device. 

Unfortunately I couldn't get 0.36 or earlier running for some reason, but it still reproduces on 0.39.

**Comment by Chooin** [comment] 2016-12-07 14:47
Useing Linking

**Comment by anarchicknight** [comment] 2016-12-08 20:08
Will take another look (hopefully this weekend) and try and debug in simulator thanks. Last time I ran on ios (ios9) the simulator did not launch for phonecalls at all

**Comment by anarchicknight** [comment] 2016-12-11 21:10
@atdrago How do you reproduce it in the simulator?

I am trying and get the same error I have always had about the simulator not being able to open the url scheme, because the dealer cannot be launched in the simulator

**Comment by anarchicknight** [comment] 2016-12-11 22:02
OK - got my hands on an iOS 10 device. Managed to replicate. It is because cancelling the prompt causes react-native to think there was an error from the openURL method in their Linking module which this library uses, and I use a console.error to report this.

I can do a bit of a work around for this and ignore the error only if the prompt option is true.

Will work on this and get it published shortly

**Comment by anarchicknight** [comment] 2016-12-11 22:19
resolved with 2.1.4

**Closed by anarchicknight** 2016-12-11 22:19 UTC
