### ISSUE TITLE
Communications.text is crashing app

### ISSUE THREAD

**Issue by mikenpeacock** [anarchicknight/react-native-communications#55] opened 2017-04-28 12:19 UTC
Not 100% sure whats happening but after communications.text is executed the calling app crashes, but my text does populate in my messenger 👍 Using an android physical device to test. Also here is my package.json file: 

```
{
  "name": "manager",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "eslint-config-rallycoding": "^3.1.0",
    "firebase": "^3.4.1",
    "lodash": "^4.16.4",
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-communications": "2.2.1",
    "react-native-router-flux": "3.35.0",
    "react-redux": "4.4.5",
    "redux": "3.6.0",
    "redux-thunk": "2.1.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "eslint-config-rallycoding": "^3.2.0",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by anarchicknight** [comment] 2017-04-30 21:34
can you provide a small sample project which will replicate the issue please?

Also, what device and OS version are you having the issue on?

Thanks

**Comment by mikenpeacock** [comment] 2017-05-01 12:10
Using a Galaxy S7, Also tested with Nexus 5 Emulator, on the emulator it does not crash. Will link a project that replicates issue later today

**Comment by anarchicknight** [comment] 2017-05-03 21:08
Thanks for the info.

Can I also ask that you check if the issue happens just using the Linking library directly from react-native? If it does then nothing can be done for this library as it is just a wrapper on top of Linking from RN

**Comment by anarchicknight** [comment] 2017-07-30 12:29
@mikenpeacock Did you ever find out if the same issue happened just using the Linking library from React Native?

**Comment by anarchicknight** [comment] 2017-11-01 10:37
Closing due to age and no reproducible steps

**Closed by anarchicknight** 2017-11-01 10:37 UTC
