### ISSUE TITLE
Body in text-method gets encoded with special characters

### ISSUE THREAD

**Issue by daemir** [anarchicknight/react-native-communications#43] opened 2017-01-10 20:38 UTC
Example: 
`
const myText = 'This is awesome!';
...
text(number, myText);
`

Output of myText in the messaging app is:
`This%20is%20awesome!`

Any way to quick fix this?

Running on iPhone 6

**Comment by anarchicknight** [comment] 2017-01-10 21:02
Interesting.

Can you let me know what version of the library you are using, also what version of RN and what iOS version.

Running on RN 0.40 with the latest version of this library (2.1.4) on iPhone 6 iOS10.2 does not replicate the issue

**Comment by daemir** [comment] 2017-01-10 21:35
We are currently running RN 0.35 and library version 2.1.4

**Comment by anarchicknight** [comment] 2017-01-10 21:51
Thanks.

Just created another test project using RN 0.35 and I still cannot replicate the issue.

Are you able to provide the full code of how the text is generated and then the method called without giving away any of your intellectual property?

e.g. this is how I am testing and does not replicate the issue

```import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableOpacity,
  View
} from 'react-native';
import { text } from 'react-native-communications'

export default class CommsTest extends Component {
  render() {
    const myText = 'A string with spaces!'
    return (
      <View style={styles.container}>
      <TouchableOpacity onPress={() => text('12345', myText)}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        </TouchableOpacity>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}
```

**Comment by daemir** [comment] 2017-01-11 08:45
Here is my code: 

```
import { text } from 'react-native-communications';
...
  onContactPress(phoneNumber) {
    const inviteText = 'JOIN MYAPP TODAY!';
    text(phoneNumber, inviteText);
  }

  renderRow(rowData) {
      const phoneNumber = rowData.phoneNumbers[0].number;
      return (
        <TouchableOpacity style={styles.row} onPress={ () => this.onContactPress(phoneNumber)}>
          <Text style={styles.text}>{rowData.familyName} {rowData.givenName}</ Text>
          <Text style={styles.smallText}>{phoneNumber}</ Text>
        </TouchableOpacity>
      );
  }
```

**Comment by anarchicknight** [comment] 2017-01-11 21:24
Ok just tried using your approach and I still do not get it showing %20. My text in the messages app shows correctly with spaces.

At a bit of a loss to be honest now. I can't replicate using the same code and setup. Not had any other reports of it being an issue for other people either.

Can you still replicate with your setup if you break the code down to the simplest example as I provided earlier?

**Comment by pmwisdom** [comment] 2017-01-12 05:53
Hey @anarchicknight. Great plugin man, having the same issue though. Just thought I'd report it. Very similar use case and code as yours above.

Oh this is on android. Haven't tested on IOS yet.

**Comment by anarchicknight** [comment] 2017-01-12 21:41
This is a weird one. I can definitely see why my code would produce %20 for spaces as I use encodeURIComponent() in the text method (due to a previous issue a user had when trying to include a url in the message text) but I cannot seem to replicate the issue at all on my test devices (emulator, iPhone 6, LG G5).

As a quick fix I may just add a new method which uses the pure text and does not encode it at all so you guys can make use of that, but as a proper solution, perhaps over the weekend I will look at trying to condense it all in to the original text method and provide an optional encode parameter (would have to be true by default not to break peoples existing use cases)

**Comment by anarchicknight** [comment] 2017-01-12 21:53
Interestingly, if I do a console log then the string does show the %20 characters for the string but then in the actual messages app of the device it seems they are removed and it displays as you would expect.

Are you seeing the issue within the messaging app or within a log?

**Comment by pmwisdom** [comment] 2017-01-13 03:18
Yeah its in the messaging app. Just the plain old regular one on the Samsung s6 edge.

**Comment by anarchicknight** [comment] 2017-01-13 20:57
2.2.0 has been released with a new method `textWithoutEncoding` as a temporary workaround which you both can use. Keep in mind that if you have any text for the message which needs encoding (e.g. web urls) then you will be responsible for encoding yourself before passing to the method.

Can you give it a go and let me know if this solves it for you in the short term?

I am going to be working on a V3 of the library which will include a major overhaul of all methods

**Comment by anarchicknight** [comment] 2017-01-28 13:56
closing this as it provides a workaround for now

**Closed by anarchicknight** 2017-01-28 13:56 UTC

**Comment by kcalmes** [comment] 2017-07-13 02:20
@anarchicknight This workaround works for me. Ironically I am using it so a url is not encoded so a url can be sent in a text message. Using the other message the url is encoded and is not a valid link in the text message. So I have a noob question, because you said if I have a url I will need to encode on my own. My question is, why would I ever need to url encode anything when sending a text message?

**Comment by alexgsummer** [comment] 2018-08-22 01:53
@anarchicknight I came across this issue and just wanted to offer up a suggestion. I could be wrong, but I checked out the [relevant code](https://github.com/anarchicknight/react-native-communications/blob/13aed9b832104d1746a272c2e5a9026b22350125/AKCommunications.js#L131) and I believe the issue is that you are URL encoding the entire message body. My guess is that only URIs within the message body should be encoded. This would require you to parse the message body text, identify URIs, encode them and replace the original non-encoded URI with an encoded one.

Your solution of providing a non encoded version allows users of this API to encode URIs themself and also means you don't have to worry about doing what I mentioned above. 👍
